# -- GitOps Core: Repositorio GitOps --
# Secret para que ArgoCD pueda acceder al repo de GitHub
apiVersion: v1
kind: Secret
metadata:
  name: repository-devops
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: DevOps
  url: https://github.com/NicoMiretti/devops.git
  type: git
